config:
  settings:
    title: My Homelab
    theme: dark
    layout:
      Docs:
        style: row
        columns: 3

  services:
    - Monitoring:
        - Grafana:
            href: http://172.18.0.2:3000
            description: Metrics dashboards
            icon: grafana.png
            namespace: monitoring
    - Mealie:
        - Mealie:
            href: http://172.18.0.2:9000
            description: Recipe manager
            icon: mealie.png
            namespace: mealie
    - Git:
        - GitHub:
            - description: brianemm99
              href: https://github.com/brianemm99
              icon: github-light.png
        - Codeberg:
            - description: brianemm99
              href: https://codeberg.org/brianemm99
              icon: codeberg.png


  bookmarks:
    - Docs:
        - Kubernetes:
            - href: https://kubernetes.io/docs/home/
              icon: kubernetes.png
        - Helm:
            - href: https://helm.sh/docs/
              icon: helm.png
        - K3s:
            - href: https://docs.k3s.io/
              icon: k3s.png
        - Arch:
            - href: https://wiki.archlinux.org/title/Main_page
              icon: arch-linux.png
        - Hyprland:
            - href: https://wiki.hypr.land/
              icon: hyprland.png
        - Quickshell:
            - abbr: QS
              href: https://quickshell.org/

  widgets:
    - search:
        provider: brave
        focus: true # Optional, will set focus to the search bar on page load
        showSearchSuggestions: true # Optional, will show search suggestions. Defaults to false
        target: _blank # One of _self, _blank, _parent or _top
    - resources:
        cpu: true
        cputemp: true
        memory: true
    - datetime:
        text_size: 2xl
        format:
          timeStyle: short
          hourCycle: h23

env:
  - name: HOMEPAGE_ALLOWED_HOSTS
    value: 172.18.0.2:3001

