#!/bin/bash
set -euo pipefail
cd "$(dirname "$0")/.."

# docker-in-docker daemon
sudo update-alternatives --set iptables /usr/sbin/iptables-nft
sudo update-alternatives --set ip6tables /usr/sbin/ip6tables-nft

/home/vscode/.local/bin/mise trust
